In [4]:
import numpy as np

In [5]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
arr=np.arange(0,20)

In [19]:
arr1=arr[0:6]

In [20]:
arr1

array([0, 1, 2, 3, 4, 5])

Broadcasting

In [21]:
arr1[:]=10

In [22]:
arr

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
arr_copy=arr.copy()

In [24]:
arr_copy

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
arr_copy[:]=100

In [26]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [27]:
arr

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
arr_2d=np.array([[2,4],[5,6]])

In [30]:
arr_2d

array([[2, 4],
       [5, 6]])

In [32]:
arr_2d[1,1]

6

In [34]:
arr_2d[:1,1:]

array([[4]])

In [35]:
arr_2d.shape

(2, 2)

In [37]:
arr=np.arange(0,11)

In [38]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [39]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr<5]

array([0, 1, 2, 3, 4])

In [43]:
arr_2d=np.arange(50).reshape(5,10)

In [44]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [46]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])