In [6]:
import numpy as np

In [7]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
np.arange(0,4)

array([0, 1, 2, 3])

In [11]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [13]:
np.ones(2)

array([1., 1.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.93721651, 0.16141065, 0.12135517, 0.53464892, 0.49908951])

In [20]:
np.random.randn(2)

array([-0.7681161 ,  2.48216189])

In [21]:
np.random.randint(1,100)

48

In [22]:
arr=map(lambda x:x*2,np.arange(10))

In [23]:
arr

In [24]:
list(arr)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [31]:
arr=np.arange(25).reshape(5,5)

In [32]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr.max()

24

In [33]:
arr.argmin()

0

In [35]:
arr.shape

(5, 5)

In [36]:
arr.dtype

dtype('int64')